spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver  # 데이터베이스 커넥션 소스 설정 완료, HikariCP가 다 걸어줌
  jpa:
    hibernate:
      ddl-auto: create                # 자동으로 테이블을 만들어 줌?
    properties:
      hibernate:
        # show_sql: true              # System.out으로 Log를 남김(비추천)
        format_sql: true
logging.level:
    org.hibernate.SQL: debug          # hibernate가 생성하는 SQL 모두를 Log로 남김
    org.hibernate.type: trace         # SQL 실행 파라미터를 로그로 남김